### ISSUE TITLE
Typo on the Special Passage Section

### ISSUE THREAD

**Issue by manonamora** [SjoerdHekking/Sugarcube2-kiras-guide#2]
> StoryHeader: this loads its contents before the current passage.
> StoryFooter: this loads its contents after the current passagae, but before StoryCaption

It should be Passage and not Story for the name (also a typo on passage last line) :)

**Comment by SjoerdHekking** [comment]
Commit c446176 solved it!

**Comment by SjoerdHekking** [comment]
Commit c446176 solved it!
